# NSE Codes for Companies
# nseCodes = ('IOC','ONGC','BEL','BHEL','RCF','ABSLAMC','BSE')
test = ('IOC','BEL')

# As of 9 Aug 2025

# Nifty 50
# Checked
# 4 issues = 3 empty 1 null
# Success
N50 = (
    "RELIANCE", "HDFCBANK", "BHARTIARTL", "TCS", "ICICIBANK", "SBIN", "INFY", "HINDUNILVR", "BAJFINANCE",
    "ITC", "LT", "HCLTECH", "MARUTI", "M&M", "KOTAKBANK", "SUNPHARMA", "ULTRACEMCO", "AXISBANK", "NTPC",
    "TITAN", "BAJAJFINSV", "ONGC", "ADANIPORTS", "BEL", "GRASIM", "JSWSTEEL", "POWERGRID", "DIVISLAB", 
    "NESTLEIND", "TATACONSUM", "BRITANNIA", "DRREDDY", "SBILIFE", "TATAMOTORS", "EICHERMOT", "BPCL",
    "HINDALCO", "COALINDIA", "APOLLOHOSP", "CIPLA", "TATASTEEL", "HEROMOTOCO", "HDFCLIFE", "UPL", "WIPRO",
    "SHRIRAMFIN", "ADANIENT", "TECHM", "ASIANPAINT", "HDFC", "JIOFIN", "TRENT", "ETERNAL"
)

# Nifty Next 50
# Checked
# 1 issues = 1 empty
# Success
NN50 = (
    "ABB", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "AMBUJACEM", "BAJAJHLDNG", "BAJAJHFL", "BANKBARODA", "BPCL",
    "BRITANNIA", "BOSCHLTD", "CANBK", "CGPOWER", "CHOLAFIN", "DABUR", "DIVISLAB", "DLF", "DMART",
    "GAIL", "GODREJCP", "HAVELLS", "HAL", "HYUNDAI", "ICICIGI", "ICICIPRULI", "INDHOTEL", "IOC",
    "INDIGO", "NAUKRI", "IRFC", "JINDALSTEL", "JSWENERGY", "LICI", "LODHA", "LTIM", "PIDILITIND",
    "PFC", "PNB", "RECLTD", "MOTHERSON", "SHREECEM", "SIEMENS", "SWIGGY", "TATAPOWER", "TORNTPHARM",
    "TVSMOTOR", "UNITDSPR", "VBL", "VEDL", "ZYDUSLIFE"
)

# NIFTY 100
# Checked
# 5 issues = 4 empty 1 null
# Success
N100 = (
    "RELIANCE", "HDFCBANK", "BHARTIARTL", "TCS", "ICICIBANK", "SBIN", "INFY", "HINDUNILVR", "BAJFINANCE", "ITC",
    "LT", "HCLTECH", "MARUTI", "M&M", "KOTAKBANK", "SUNPHARMA", "ULTRACEMCO", "AXISBANK", "NTPC", "TITAN",
    "BAJAJFINSV", "ONGC", "ADANIPORTS", "BEL", "GRASIM", "JSWSTEEL", "POWERGRID", "DIVISLAB", "NESTLEIND", "TATACONSUM",
    "BRITANNIA", "DRREDDY", "SBILIFE", "TATAMOTORS", "EICHERMOT", "BPCL", "HINDALCO", "COALINDIA", "APOLLOHOSP", "CIPLA",
    "TATASTEEL", "HEROMOTOCO", "HDFCLIFE", "UPL", "WIPRO", "SHRIRAMFIN", "ADANIENT", "TECHM", "ASIANPAINT", "HDFC",
    "JIOFIN", "TRENT", "ETERNAL", "ABB", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "AMBUJACEM", "BAJAJHLDNG",
    "BAJAJHFL", "BANKBARODA", "BOSCHLTD", "CANBK", "CGPOWER", "CHOLAFIN", "DABUR", "DLF", "DMART", "GAIL",
    "GODREJCP", "HAVELLS", "HAL", "HYUNDAI", "ICICIGI", "ICICIPRULI", "INDHOTEL", "IOC", "INDIGO", "NAUKRI",
    "IRFC", "JINDALSTEL", "JSWENERGY", "LICI", "LODHA", "LTIM", "PIDILITIND", "PFC", "PNB", "RECLTD",
    "MOTHERSON", "SHREECEM", "SIEMENS", "SWIGGY", "TATAPOWER", "TORNTPHARM", "TVSMOTOR", "UNITDSPR", "VBL", "VEDL",
    "ZYDUSLIFE"
)

# NIFTY BANK
# Checked
# 1 issues = 1 empty
# Success
Nbank = (
    "SBIN", "ICICIBANK", "IDFCFIRSTB", "AUBANK", "AXISBANK", "BANDHANBNK",
    "FEDERALBNK", "HDFCBANK", "INDUSINDBK", "KOTAKBANK", "PNB", "RBLBANK"
)

# NIFTY IT
# Checked
# 0 issues
# Success
Nit = (
    "TCS", "INFY", "HCLTECH", "WIPRO", "LTIM", "TECHM", "PERSISTENT", "OFSS", "MPHASIS"
)

# NIFTY FMCG
# Checked
# 3 issues = 3 empty
# Success
Nfmcg = (
    "NESTLEIND", "PATANJALI", "EMAMILTD", "VBL", "UNITDSPR","UBL", "TATACONSUM", "RADICO", 
    "MARICO", "ITC", "HINDUNILVR", "BRITANNIA"
)

# NIFTY AUTO
# Checked
# 0 issues
# Success
Nauto = (
    "TATAMOTORS", "BAJAJ-AUTO", "EICHERMOT", "TVSMOTOR", "BOSCHLTD", "MOTHERSON", "EICHERMOT", "HEROMOTOCO"
)

# NIFTY METAL
# Checked
# 5 issues = 2 empty 3 null
# Success
Nmetal = (
    "ADANIENT", "JSWSTEEL", "TATASTEEL", "HINDZINC", "VEDL",
    "SAIL", "HINDCOPPER", "NMDC", "TATAMETALI", "COCHINSHIP",
    "METROPOLIS", "ITC", "JINDALSTEL", "WELCORP", "CASTROLIND"
)

# NIFTY PHARMA
# Checked
# 0 issues
# Success
Npharma = (
    "LUPIN", "ABBOTINDIA", "AUROPHARMA", "CIPLA", "DRREDDY", "GLENMARK",
    "DIVISLAB", "ALKEM", "SANOFI"
)

# Nifty Midcap Select (25 companies)
# Checked
# 2 issues = 1 empty 1 null
# Success
NMS = (
    "MAXHEALTH", "HDFCAMC", "CUMMINSIND", "POLYCAB", "BSE", "DIXON", "MARICO",
    "INDUSTOWER", "LUPIN", "HINDPETRO", "SRF", "PERSISTENT", "BHARATFORG", "YESBANK",
    "COFORGE", "MPHASIS", "VOLTAS", "MUTHOOTFIN", "AUROPHARMA", "COLPAL",
    "GODREJPROP", "ASHOKLEY", "BAJAJHLDNG", "GLENMARK", "DRREDDY"
)

# Nifty Midcap 50
NM50 = (
    "MAXHEALTH", "HDFCAMC", "CUMMINSIND", "MUTHOOTFIN", "POLYCAB", "BSE", "DIXON", "GMRINFRA", "MARICO",
    "INDUSTOW", "LUPIN", "HINDPETRO", "SRF", "PERSISTENT", "BHARATFORG", "YESBANK", "COFORGE", "MPHASIS",
    "VOLTAS", "AUROPHARMA", "COLPAL", "GODREJPROP", "ASHOKLEY", "BAJAJHLDNG", "GLENMARK", "DRREDDY", "NHPC",
    "PBFINTECH", "HAVELLS", "HCLTECH", "CANBK", "IOC", "BANKBARODA", "SIEMENS", "TATAPOWER", "TORNTPHARM",
    "TVSMOTOR", "ADANIENT", "UPL", "TITAN", "INDIGO", "NAUKRI", "LICI", "LODHA", "PNB",
    "SHREECEM", "TATASTEEL", "MOTHERSON"
)

# Nifty Midcap 100
NM100 = (
    "HINDZINC", "SOLARINDS", "MAXHEALTH", "HDFCAMC", "MAZDOCK", "CUMMINSIND", "MUTHOOTFIN", "MANKINDPHA", "POLYCAB",
    "UNIONBANK", "BSE", "DIXON", "GMRINFRA", "MARICO", "HITACHIELE", "INDUSTOW", "WAAREE", "BHARATHEX",
    "INDIAN", "LUPIN", "HINDPETRO", "SUZLON", "NTPC", "SRF", "NHPC", "DABUR", "HAVELLS",
    "DMART", "GODREJCP", "PIDILITIND", "API", "BERGEPAINT", "NESTLEIND", "MAHABANK", "BAJAJHFL", "ESCORTS",
    "MINDTREE", "JINDALSTEL", "BANKBARODA", "TECHM", "CANBK", "EICHERMOT", "ICICIGI", "AUROPHARMA", "TATASTEEL",
    "TORNTPHARM", "LICI", "OBEROIRLTY", "LTI", "BALRAMCHIN", "DEEPAKFERT", "BRAHMAPUTRA", "GAIL", "COLPAL",
    "MCDOWELL_N", "ADANIPORTS", "MOTHERSUMI", "BRIGADE", "TEJASNET", "MCLEODRUSS", "MOIL", "EXIDEIND", "CRISIL",
    "BALKRISHNA", "ABBOTINDIA", "VOLTAS", "SUZLON", "INDIGO", "HUDCO", "TATASTEEL", "SRF", "CAPLIPOINT",
    "MUTHOOTFIN", "ASHOKLEY", "HINDUNILVR", "HINDPETRO", "M&M", "HINDALCO", "VOLTAS", "LUPIN", "PIDILITIND",
    "TITAN", "NAUKRI", "SBIN", "IDFCFIRSTB", "HDFCBANK", "ICICIBANK", "KOTAKBANK", "AXISBANK", "BAJFINANCE"
)

NS50 = (
    "LAURUSLABS", "MULTI", "KAYNESTEC", "RADICO", "DELV", "POONAWALLA", "CDSL", "ASTERDM", "NBCC",
    "AFFLE", "LALPATHLAB", "FIRSTSOURCE", "PIRAMALENT", "RAMCOSYS", "RAMKY", "AARTIIND", "AMARAJABAT", "ATUL",
    "AIAENG", "MIRZAINT", "NAVINFLUOR", "INOXWIND", "TATACHEM", "BRIGADE", "ANGELONE", "HINDCOPPER", "HIMATSEIDE",
    "CESC", "AAVAS", "CROMPGREAV", "CYIENT", "CENTRALDEPO", "RITES", "KAJARIACER", "INDIAGLYCO", "ZENSARTECH",
    "TV18BRDCST", "GUJGASLTD", "ICRA", "INDIANB", "IDBI", "DLF", "ECLERX", "EIHOTEL", "HAPPSTMNDS",
    "HATHWAY", "TRIDENT", "TATAMTRDVR", "GODFRYPHLP", "SOBHA", "SOLARA", "RELINFRA", "SIS", "SOBHA",
    "VGUARD", "KALYANKJIL", "IOLCP", "IRCTC", "JUBLFOOD", "JKCEMENT", "JKLAKSHMI", "JSWENERGY", "KPRMILL",
    "LTI", "MINDTREE", "MOTHERSUMI", "NAM-INDIA", "NASPANTHAL", "NAVINFLUOR", "NELCO", "NIITTECH", "POLYMED",
    "PRESTIGE", "PRSMJOHNSN", "RACLGEAR", "RAMCOCEM", "RAIN", "RAMKY", "REDINGTON", "SAIL", "SANOFI",
)


NS100 = (
    "IDBI", "GODFRYPH", "LAURUSLABS", "MCX", "KAYNES", "RADICO", "NARAYANA", "DELV", "POONAWALLA",
    "GODIGIT", "CDSL", "ASTERDM", "ITI", "GRSE", "NBCC", "AFFLE", "INVEST", "DRLALPATH",
    "SHYAMMETL", "FSL", "PIRAMALENT", "RAMCOSYS", "RAMKY", "AARTIIND", "AMARAJABAT", "ATUL", "AIAENG",
    "MIRZAINT", "NAVINFLUOR", "INOXWIND", "TATACHEM", "BRIGADE", "ANGELONE", "HINDCOPPER", "HIMATSEIDE", "CESC",
    "AAVAS", "CROMPGREAV", "CYIENT", "CENTRALDEPO", "RITES", "KAJARIACER", "INDIAGLYCO", "ZENSARTECH", "TV18BRDCST",
    "GUJGASLTD", "ICRA", "INDIANB", "IDBI", "DLF", "ECLERX", "EIHOTEL", "HAPPSTMNDS", "HATHWAY",
    "TRIDENT", "TATAMTRDVR", "GODFRYPHLP", "SOBHA", "SOLARA", "RELINFRA", "SIS", "VGUARD", "KALYANKJIL",
    "IOLCP", "IRCTC", "JUBLFOOD", "JKCEMENT", "JKLAKSHMI", "JSWENERGY", "KPRMILL", "LTI", "MINDTREE",
    "MOTHERSUMI", "NAM-INDIA", "NASPANTHAL", "NAVINFLUOR", "NELCO", "NIITTECH", "POLYMED", "PRESTIGE", "PRSMJOHNSN",
    "RACLGEAR", "RAMCOCEM", "RAIN", "RAMKY", "REDINGTON", "SAIL", "SANOFI", "CASTROLIND", "SONATA",
    "TEJASNET", "WELSPUNLIV", "PVR", "HFCL", "RAMKRISHNA", "BIRLASOFT", "ANANTRAJ", "AFCONS", "IFCI"
)





# Note: This is a partial list for illustration; the full list contains 150 companies.
# Nifty Midcap 150 (150 companies, partial list shown here)
NM150 = (
    "HINDZINC", "SOLARINDS", "MAXHEALTH", "HDFCAMC", "MAZDOCK", "CUMMINSIND", "MUTHOOTFIN",
    "MANKIND", "POLYCAB", "UNIONBANK", "BSE", "DIXON", "GMRAIRPORT", "MARICO",
    "POWERINDIA", "INDUSTOW", "WAAREE", "BHARATHEX", "INDIAN", "LUPIN", "HINDPETRO",
    "SUZLON", "NTPC", "SRF", "NHPC", "DABUR", "HAVELLS", "DMART",
    "GODREJCP", "PIDILITIND", "API", "BERGEPAINT", "NESTLEIND", "MAHABANK",
    "BAJAJHFL", "ESCORTS", "PIDILITIND", "MINDTREE", "JINDALSTEL", "BANKBARODA",
    "TECHM", "CANBK", "EICHERMOT", "ICICIGI", "AUROPHARMA", "TATASTEEL", "TORNTPHARM",
    "LICI", "OBEROIRLTY", "LTI", "BALRAMCHIN", "GMRINFRA", "DEEPAKFERT", "BRAHMAPUTRA",
    "GAIL", "PIDILITIND", "COLPAL", "MCDOWELL_N", "ADANIPORTS", "LUPIN", "MOTHERSUMI",
    "BRIGADE", "TEJASNET", "MCLEODRUSS", "MOIL", "AUROPHARMA", "EXIDEIND", "LTI",
    "CRISIL", "BALKRISHNA", "ABBOTINDIA", "ESCORTS", "VOLTAS", "COLPAL", "SUZLON",
    "DABUR", "PIDILITIND", "INDIGO", "HUDCO", "LUPIN", "TATASTEEL", "SRF", "HDFCAMC",
    "CAPLIPOINT", "MUTHOOTFIN", "ASHOKLEY", "HINDUNILVR", "HINDPETRO", "M&M", "HINDALCO", "VOLTAS"
)