# NSE Codes for Companies
# nseCodes = ('IOC','ONGC','BEL','BHEL','RCF','ABSLAMC','BSE')
test = ('IOC','BEL')

# As of 9 Aug 2025

# Nifty 50
N50 = (
    "RELIANCE", "HDFCBANK", "BHARTIARTL", "TCS", "ICICIBANK", "SBIN", "INFY", "HINDUNILVR", "BAJFINANCE",
    "ITC", "LT", "HCLTECH", "MARUTI", "M&M", "KOTAKBANK", "SUNPHARMA", "ULTRACEMCO", "AXISBANK", "NTPC",
    "TITAN", "BAJAJFINSV", "ONGC", "ADANIPORTS", "BEL", "GRASIM", "JSWSTEEL", "POWERGRID", "DIVISLAB", 
    "NESTLEIND", "TATACONSUM", "BRITANNIA", "DRREDDY", "SBILIFE", "TATAMOTORS", "EICHERMOT", "BPCL",
    "HINDALCO", "COALINDIA", "APOLLOHOSP", "CIPLA", "TATASTEEL", "HEROMOTOCO", "HDFCLIFE", "UPL", "WIPRO",
    "SHRIRAMFIN", "ADANIENT", "TECHM", "ASIANPAINT", "HDFC", "JIOFIN", "TRENT", "ETERNAL"
)

# Nifty Next 50
NN50 = (
    "ABB", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "AMBUJACEM", "BAJAJHLDNG", "BAJAJHFL", "BANKBARODA", "BPCL",
    "BRITANNIA", "BOSCHLTD", "CANBK", "CGPOWER", "CHOLAFIN", "DABUR", "DIVISLAB", "DLF", "DMART",
    "GAIL", "GODREJCP", "HAVELLS", "HAL", "HYUNDAI", "ICICIGI", "ICICIPRULI", "INDHOTEL", "IOC",
    "INDIGO", "NAUKRI", "IRFC", "JINDALSTEL", "JSWENERGY", "LICI", "LODHA", "LTIM", "PIDILITIND",
    "PFC", "PNB", "RECLTD", "MOTHERSON", "SHREECEM", "SIEMENS", "SWIGGY", "TATAPOWER", "TORNTPHARM",
    "TVSMOTOR", "UNITDSPR", "VBL", "VEDL", "ZYDUSLIFE"
)

# NIFTY 100
N100 = (
    "RELIANCE", "HDFCBANK", "BHARTIARTL", "TCS", "ICICIBANK", "SBIN", "INFY", "HINDUNILVR", "BAJFINANCE", "ITC",
    "LT", "HCLTECH", "MARUTI", "M&M", "KOTAKBANK", "SUNPHARMA", "ULTRACEMCO", "AXISBANK", "NTPC", "TITAN",
    "BAJAJFINSV", "ONGC", "ADANIPORTS", "BEL", "GRASIM", "JSWSTEEL", "POWERGRID", "DIVISLAB", "NESTLEIND", "TATACONSUM",
    "BRITANNIA", "DRREDDY", "SBILIFE", "TATAMOTORS", "EICHERMOT", "BPCL", "HINDALCO", "COALINDIA", "APOLLOHOSP", "CIPLA",
    "TATASTEEL", "HEROMOTOCO", "HDFCLIFE", "UPL", "WIPRO", "SHRIRAMFIN", "ADANIENT", "TECHM", "ASIANPAINT", "HDFC",
    "JIOFIN", "TRENT", "ZOMATO", "ABB", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "AMBUJACEM", "BAJAJHLDNG",
    "BAJAJHFL", "BANKBARODA", "BOSCHLTD", "CANBK", "CGPOWER", "CHOLAFIN", "DABUR", "DLF", "DMART", "GAIL",
    "GODREJCP", "HAVELLS", "HAL", "HYUNDAI", "ICICIGI", "ICICIPRULI", "INDHOTEL", "IOC", "INDIGO", "NAUKRI",
    "IRFC", "JINDALSTEL", "JSWENERGY", "LICI", "LODHA", "LTIM", "PIDILITIND", "PFC", "PNB", "RECLTD",
    "MOTHERSON", "SHREECEM", "SIEMENS", "SWIGGY", "TATAPOWER", "TORNTPHARM", "TVSMOTOR", "UNITDSPR", "VBL", "VEDL",
    "ZYDUSLIFE"
)

# NIFTY BANK
Nbank = (
    "SBIN", "ICICIBANK", "IDFCFIRSTB", "AUBANK", "AXISBANK", "BANDHANBNK",
    "FEDERALBNK", "HDFCBANK", "INDUSINDBK", "KOTAKBANK", "PNB", "RBLBANK"
)

# NIFTY IT
Nit = (
    "TCS", "INFY", "HCLTECH", "WIPRO", "LTIM", "TECHM", "PERSISTENT", "OFSS", "MPHASIS"
)

# NIFTY FMCG
Nfmcg = (
    "NESTLEIND", "PATANJALI", "EMAMILTD", "VBL", "UNITDSPR","UBL", "TATACONSUM", "RADICO", 
    "MARICO", "ITC", "HINDUNILVR", "BRITANNIA"
)

# NIFTY AUTO
Nauto = (
    "TATAMOTORS", "BAJAJ_AUTO", "EICHERMOT", "TVSMOTOR", "BOSCHLTD", "MOTHERSON", "EICHERMOT", "HEROMOTOCO"
)

# NIFTY METAL
Nmetal = (
    "ADANIENT", "JSWSTEEL", "TATASTEEL", "HINDZINC", "VEDL",
    "SAIL", "HINDCOPPER", "NMDC", "TATAMETALI", "COCHINSHIP",
    "METROPOLIS", "ITC", "JINDALSTEL", "WELCORP", "CASTROLIND"
)

# NIFTY PHARMA
Npharma = (
    "LUPIN", "ABBOTINDIA", "AUROPHARMA", "CIPLA", "DRREDDY", "GLENMARK",
    "DIVISLAB", "CADILAHC", "ALKEM", "SANOFI", "BIOSPHERE", "TATAPHARM"
)

# Nifty Midcap Select (25 companies)
NMS = (
    "MAXHEALTH", "HDFCAMC", "CUMMINSIND", "POLYCAB", "BSE", "DIXON", "MARICO",
    "INDUSTOW", "LUPIN", "HINDPETRO", "SRF", "PERSISTENT", "BHARATFORG", "YESBANK",
    "COFORGE", "MPHASIS", "VOLTAS", "MUTHOOTFIN", "AUROPHARMA", "COLPAL",
    "GODREJPROP", "ASHOKLEY", "BAJAJHLDNG", "GLENMARK", "DRREDDY"
)

# Note: This is a partial list for illustration; the full list contains 150 companies.
# Nifty Midcap 150 (150 companies, partial list shown here)
NM150 = (
    "HINDZINC", "SOLARINDS", "MAXHEALTH", "HDFCAMC", "MAZDOCK", "CUMMINSIND", "MUTHOOTFIN",
    "MANKINDPHA", "POLYCAB", "UNIONBANK", "BSE", "DIXON", "GMRINFRA", "MARICO",
    "HITACHIELE", "INDUSTOW", "WAAREE", "BHARATHEX", "INDIAN", "LUPIN", "HINDPETRO",
    "SUZLON", "NTPC", "SRF", "NHPC", "DABUR", "HAVELLS", "DMART",
    "GODREJCP", "PIDILITIND", "API", "BERGEPAINT", "NESTLEIND", "MAHABANK",
    "BAJAJHFL", "ESCORTS", "PIDILITIND", "MINDTREE", "JINDALSTEL", "BANKBARODA",
    "TECHM", "CANBK", "EICHERMOT", "ICICIGI", "AUROPHARMA", "TATASTEEL", "TORNTPHARM",
    "LICI", "OBEROIRLTY", "LTI", "BALRAMCHIN", "GMRINFRA", "DEEPAKFERT", "BRAHMAPUTRA",
    "GAIL", "PIDILITIND", "COLPAL", "MCDOWELL_N", "ADANIPORTS", "LUPIN", "MOTHERSUMI",
    "BRIGADE", "TEJASNET", "MCLEODRUSS", "MOIL", "AUROPHARMA", "EXIDEIND", "LTI",
    "CRISIL", "BALKRISHNA", "ABBOTINDIA", "ESCORTS", "VOLTAS", "COLPAL", "SUZLON",
    "DABUR", "PIDILITIND", "INDIGO", "HUDCO", "LUPIN", "TATASTEEL", "SRF", "HDFCAMC",
    "CAPLIPOINT", "MUTHOOTFIN", "ASHOKLEY", "HINDUNILVR", "HINDPETRO", "M&M", "HINDALCO", "VOLTAS"
)