# FUTURE SCOPE FOR THIS PROJECT

# TO CREATE FUNCTIONS WHICH WILL ADD DATA TO CSV FOR STOCK

# IF EXISTS REMOVE OLD AND ADD LATEST DATA FOR THAT

# ANY IDEAS FOR INDEXING FOR CSV ARE WELCOME

# JSON ARE BETTER FOR FETCHING DATA AND CREATING ENDPOINTS

# BUT CSV WILL BE USEFULL MODEL BUILDING